basePath: /
definitions:
  github_com_dimasbaguspm_infario_pkgs_response.ErrorResponse:
    description: Standard API error response
    properties:
      errors:
        additionalProperties:
          type: string
        description: Detailed field errors
        type: object
      message:
        description: Human readable summary
        type: string
      status:
        description: HTTP Status Code
        type: integer
    type: object
  internal_resources_project.CreateProject:
    description: Project creation DTO
    properties:
      git_provider:
        enum:
        - github
        - gitlab
        - bitbucket
        type: string
      git_url:
        type: string
      name:
        maxLength: 100
        minLength: 3
        type: string
      primary_branch:
        type: string
    required:
    - git_provider
    - git_url
    - name
    type: object
  internal_resources_project.Project:
    description: Project entity representing a code repository and its metadata
    properties:
      created_at:
        type: string
      deleted_at:
        type: string
      git_provider:
        type: string
      git_url:
        type: string
      id:
        type: string
      name:
        type: string
      primary_branch:
        type: string
      updated_at:
        type: string
    type: object
  internal_resources_project.UpdateProject:
    description: Project update DTO
    properties:
      git_provider:
        enum:
        - github
        - gitlab
        - bitbucket
        type: string
      git_url:
        type: string
      id:
        type: string
      name:
        maxLength: 100
        minLength: 3
        type: string
      primary_branch:
        type: string
    required:
    - id
    type: object
host: localhost:8080
info:
  contact: {}
  description: The core API for the Infario Cloud Platform.
  title: Infario API
  version: "1.0"
paths:
  /projects:
    post:
      consumes:
      - application/json
      parameters:
      - description: Project Details
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/internal_resources_project.CreateProject'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/internal_resources_project.Project'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_dimasbaguspm_infario_pkgs_response.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_dimasbaguspm_infario_pkgs_response.ErrorResponse'
      summary: Create a project
      tags:
      - projects
  /projects/{id}:
    delete:
      parameters:
      - description: Project ID
        in: path
        name: id
        required: true
        type: string
      responses:
        "204":
          description: No Content
        "404":
          description: Project not found
          schema:
            $ref: '#/definitions/github_com_dimasbaguspm_infario_pkgs_response.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_dimasbaguspm_infario_pkgs_response.ErrorResponse'
      summary: Delete a project
      tags:
      - projects
    get:
      parameters:
      - description: Project ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal_resources_project.Project'
        "404":
          description: Project not found
          schema:
            $ref: '#/definitions/github_com_dimasbaguspm_infario_pkgs_response.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_dimasbaguspm_infario_pkgs_response.ErrorResponse'
      summary: Get a project by ID
      tags:
      - projects
    patch:
      consumes:
      - application/json
      parameters:
      - description: Project ID
        in: path
        name: id
        required: true
        type: string
      - description: Updated Project Details
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/internal_resources_project.UpdateProject'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal_resources_project.Project'
        "400":
          description: Invalid request body
          schema:
            $ref: '#/definitions/github_com_dimasbaguspm_infario_pkgs_response.ErrorResponse'
        "404":
          description: Project not found
          schema:
            $ref: '#/definitions/github_com_dimasbaguspm_infario_pkgs_response.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_dimasbaguspm_infario_pkgs_response.ErrorResponse'
      summary: Update a project
      tags:
      - projects
schemes:
- http
- https
swagger: "2.0"
